comment: false

codecov:
  token: 333d631e-26e4-4bfb-871c-e740128b0a48

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
