---
title: "Description"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Description}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# flowdex

Extract Fluorescence Distribution Data from FCS Files and Recalculate to Events per Volume

## Description

Extract fluorescence distribution data from any bivariate distribution within a previously defined flow cytometry gating strategy and **recalculate** the fluorescence distribution **to events per volume unit**.

Additionally, any number of class- and numerical variables describing the dataset can be generated by providing a structured character string in the Sample-ID field of each individual sample at the time of data acquisition. At the time of reading in the fcs files, this structured character string is translated into class- and numerical variables, using a dictionary to translate any abbreviations into its long form.

Finally, the fluorescence-distribution data that were (possibly) re-calculated to events per volume unit can be visualised and **exported to file**, along with data denoting the overall events per volume unit in each sample in each gate.

To (meaningfully) use flowdex, the fcs files have to contain volumetric measurement data denoting the acquired sample volume.

`flowdex` is leaning heavily on the packages [`flowCore`](https://rdrr.io/bioc/flowCore/) and [`flowWorkspace`](https://rdrr.io/bioc/flowWorkspace/) for data import, generation of gating sets etc.

To sum it up, package flowdex can:

-   **Extract fluorescence distribution** data from fcs files and **recalculate** them **to events per volume** unit,

-   **Generate variables** describing the dataset by using a structured character string in the sample-Id field of the sample at the time of data acquisition, and

-   Visualise fluorescence distributions and **export** them **to file**.

## Advantage

Having ones hand directly on the rawdata of fluorescence distributions is not something the average desktop GUI of FCM-machines is providing easily or willingly. Package `flowdex` was designed to alleviate that problem.

If the FCM-machine used for data acquisition does have a volumetric measurement module and the fcs files contain volumetric data, it is possible to **re-calculate any extracted fluorescence distribution to events per volume unit**.

In other words, the y-axis of any fluorescence distribution can be displayed in a fixed scale, i.e. events per volume unit. This enables the **comparison of numbers on a fixed scale** across samples, groups or experiments, **instead** of being confined to **compare percentages** of sub-groups of an overall population.

Please see the article [Re-Calculate to Events per Voliume Unit](https://bpollner.github.io/flowdex/articles/bottled_water.html) for an illustration of the benefit of being able to recalculate fluorescence distributions to sample volume.

## Two Workflow Scenarios

There are two basic scenarios when using `flowdex` that further define the appropriate workflow:

1.  Gating strategy and polygon gates are **not yet defined**.\
    Here, the focus is on [establishing the gating strategy](https://bpollner.github.io/flowdex/articles/workflow_1.html#) and manually drawing the polygon gates.

2.  Gating strategy and polygon gates are **already defined**.\
    Here, the focus is on using the previously established gating strategy to [extract fluorescence distributions](https://bpollner.github.io/flowdex/articles/workflow_2.html), visualise them and export them to file. All this (except visualisation) is conveniently done via `flowdexit()`. Look at [Quickstart](https://bpollner.github.io/flowdex/articles/flowdex.html#quickstart) for an immediate example.
